UPDATE `opcodes` SET `name`="SMSG_MOVE_GRAVITY_DISABLE" WHERE `name`="SMSG_FORCE_UNK1_SPEED_CHANGE";
UPDATE `opcodes` SET `name`="CMSG_MOVE_GRAVITY_DISABLE_ACK" WHERE `name`="CMSG_FORCE_UNK1_SPEED_CHANGE_ACK";
UPDATE `opcodes` SET `name`="SMSG_MOVE_GRAVITY_ENABLE" WHERE `name`="SMSG_FORCE_UNK2_SPEED_CHANGE";
UPDATE `opcodes` SET `name`="CMSG_MOVE_GRAVITY_ENABLE_ACK" WHERE `name`="CMSG_FORCE_UNK2_SPEED_CHANGE_ACK";